import type { Metadata } from "next";
import { Ubuntu_Sans } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const ubuntu = Ubuntu_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={ubuntu.className}
        >
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
